apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-rules
  namespace: monitoring
data:
  adapter-rules.yaml: |
    rules:
    - seriesQuery: 'container_cpu_usage_seconds_total{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: "^container_cpu_usage_seconds_total$"
        as: "pod_cpu_usage"
      metricsQuery: |
        sum by (<<.GroupBy>>) (
          rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>}[2m])
        )
