apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: hackernews
data:
  POSTGRES_DB: hackernews

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: hackernews
type: Opaque
stringData:
  POSTGRES_USER: hacker
  POSTGRES_PASSWORD: hacker123
