apiVersion: v1
kind: Pod
metadata:
  name: dns-test
  namespace: hackernews
spec:
  containers:
  - name: dns-test
    image: infoblox/dnstools:arm64
    command: ["sh"]
    stdin: true
    tty: true
